#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_student_questions.py — 批量生成学生场景新题
用法: python gen_student_questions.py
输出: 追加到 ../items.jsonl
"""
import json, re, random
from collections import Counter

random.seed(42)

# ========== 加载现有题库 ==========
BANK_PATH = 'items.jsonl'
existing = []
existing_stems = set()

def normalize(s):
    s = re.sub(r'[，。？！,. ?！]', '', s)
    s = re.sub(r'[（(][^）)]*[）)]', '', s)
    s = s.replace('②', '').strip()
    s = re.sub(r'[你我]$', '', s)
    s = re.sub(r'时$', '', s)
    return s

with open(BANK_PATH, 'r', encoding='utf-8') as f:
    for line in f:
        if line.strip():
            it = json.loads(line)
            existing.append(it)
            existing_stems.add(normalize(it['stem']))

max_id = max(int(it['id'][1:]) for it in existing)
next_id = max_id + 1
print(f'现有 {len(existing)} 题, 最大 Q{max_id:04d}, 新题从 Q{next_id:04d} 开始')

# ========== 常量 ==========
CATEGORIES = [
    'interpersonal-relationship', 'decision-making', 'stress-response',
    'motivation-value', 'learning-cognition', 'work-career',
    'emotion-self', 'action-habit', 'future-vision', 'conflict-choice',
]

VALID_THEMES = [
    'achiever', 'activator', 'adaptability', 'analytical', 'arranger', 'belief',
    'command', 'communication', 'competition', 'connectedness', 'context',
    'consistency', 'deliberative', 'developer', 'discipline', 'empathy',
    'focus', 'futuristic', 'harmony', 'ideation', 'includer',
    'individualization', 'input', 'intellection', 'learner', 'maximizer',
    'positivity', 'relator', 'responsibility', 'restorative',
    'self_assurance', 'significance', 'strategic', 'woo',
]

# 学生场景 → applicable_states
S_JUNIOR = ['academic-stress', 'study-direction']
S_SENIOR = ['academic-stress', 'study-direction', 'graduate-school']
S_UNDERGRAD = ['study-direction', 'graduate-school', 'study-abroad', 'fresh-grad', 'academic-stress']
S_GRAD = ['graduate-school', 'study-abroad', 'fresh-grad', 'career-choice']
S_PARENT = ['parenting-teen', 'academic-stress', 'study-direction']
S_ALL_STU = ['academic-stress', 'study-direction', 'graduate-school', 'study-abroad', 'fresh-grad']
S_CAREER = ['career-choice', 'fresh-grad', 'mid-career']

# 盖洛普领域映射
DOMAIN_THEMES = {
    'executing': ['achiever', 'arranger', 'belief', 'consistency', 'deliberative', 'discipline', 'focus', 'responsibility', 'restorative'],
    'influencing': ['activator', 'command', 'communication', 'competition', 'maximizer', 'self_assurance', 'significance', 'woo'],
    'relationship_building': ['adaptability', 'connectedness', 'developer', 'empathy', 'harmony', 'includer', 'individualization', 'positivity', 'relator'],
    'strategic_thinking': ['analytical', 'context', 'futuristic', 'ideation', 'input', 'intellection', 'learner', 'strategic'],
}
ALL_DOMAINS = list(DOMAIN_THEMES.keys())

# ========== 学生场景题库模板 ==========
# 每个场景: (stem, category, states_key, scale, difficulty, options_or_scoremap, themes, reverse)
# options for forced-choice: [(text, {dim:val,...}), ...]
# score_map for likert-4: {dim: [v0,v1,v2,v3]}

NEW_QUESTIONS = []

# ===== interpersonal-relationship (24题) =====
NEW_QUESTIONS += [
    # forced-choice
    ('小组作业有人不干活你', 'interpersonal-relationship', S_UNDERGRAD, 'fc', 2,
     [('直接找TA谈', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('自己多做点', {'mbti.F':2,'enneagram.type9':1,'gallup.harmony':1}),
      ('跟组长反映', {'mbti.J':1,'enneagram.type1':1,'gallup.responsibility':1}),
      ('群里委婉提醒', {'mbti.F':1,'enneagram.type2':1,'gallup.communication':1})],
     ['responsibility','harmony','command'], False),
    ('室友生活习惯让你不舒服', 'interpersonal-relationship', S_UNDERGRAD, 'fc', 2,
     [('直接说出感受', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('忍着自己适应', {'mbti.F':2,'enneagram.type9':1,'gallup.adaptability':1}),
      ('写值日表提醒大家', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('找辅导员协调', {'mbti.S':1,'enneagram.type6':1,'gallup.relator':1})],
     ['adaptability','command','discipline'], False),
    ('同学找你借作业抄', 'interpersonal-relationship', S_SENIOR, 'fc', 2,
     [('直接拒绝', {'mbti.T':2,'enneagram.type1':1,'gallup.consistency':1}),
      ('借给TA但说一下', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('讲题但不给抄', {'mbti.N':2,'enneagram.type5':1,'gallup.learner':1}),
      ('假装没写完', {'mbti.P':1,'enneagram.type4':1,'gallup.deliberative':1})],
     ['consistency','empathy','learner'], False),
    ('朋友在背后说你坏话', 'interpersonal-relationship', S_ALL_STU, 'fc', 4,
     [('当面质问', {'mbti.T':2,'enneagram.type8':2,'gallup.command':1}),
      ('慢慢疏远', {'mbti.I':2,'enneagram.type4':1,'gallup.deliberative':1}),
      ('找共同朋友了解', {'mbti.F':1,'enneagram.type6':1,'gallup.empathy':1}),
      ('反思自己问题', {'mbti.F':2,'enneagram.type1':1,'gallup.restorative':1})],
     ['command','deliberative','empathy'], False),
    ('班级竞选班委你', 'interpersonal-relationship', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('积极参选自荐', {'mbti.E':2,'enneagram.type3':2,'gallup.significance':1}),
      ('参选想为班级做事', {'mbti.F':2,'enneagram.type2':2,'gallup.responsibility':1}),
      ('不参选但配合', {'mbti.I':1,'enneagram.type9':1,'gallup.harmony':1}),
      ('不参选觉得麻烦', {'mbti.P':1,'enneagram.type5':1,'gallup.deliberative':1})],
     ['significance','responsibility','harmony'], False),
    ('和老师有意见分歧时', 'interpersonal-relationship', S_SENIOR+S_UNDERGRAD, 'fc', 3,
     [('课后找老师沟通', {'mbti.T':2,'enneagram.type1':1,'gallup.communication':1}),
      ('按老师说的做', {'mbti.S':2,'enneagram.type6':1,'gallup.harmony':1}),
      ('坚持自己做法', {'mbti.N':2,'enneagram.type8':1,'gallup.self_assurance':1}),
      ('找同学商量对策', {'mbti.E':1,'enneagram.type7':1,'gallup.woo':1})],
     ['communication','harmony','self_assurance'], False),
    ('社团里学弟学妹请教你', 'interpersonal-relationship', S_UNDERGRAD, 'fc', 2,
     [('耐心教倾囊相授', {'mbti.F':2,'enneagram.type2':2,'gallup.developer':1}),
      ('告诉方法让自己试', {'mbti.T':2,'enneagram.type5':1,'gallup.learner':1}),
      ('看情况有空就帮', {'mbti.P':1,'enneagram.type7':1,'gallup.adaptability':1}),
      ('推荐给其他人', {'mbti.E':1,'enneagram.type9':1,'gallup.harmony':1})],
     ['developer','learner','adaptability'], False),
    ('朋友考试作弊被发现', 'interpersonal-relationship', S_SENIOR, 'fc', 4,
     [('劝TA主动承认', {'mbti.F':2,'enneagram.type1':1,'gallup.consistency':1}),
      ('装作不知道', {'mbti.P':1,'enneagram.type9':2,'gallup.harmony':1}),
      ('告诉老师', {'mbti.T':2,'enneagram.type1':2,'gallup.responsibility':1}),
      ('帮TA想办法补救', {'mbti.F':1,'enneagram.type2':1,'gallup.empathy':1})],
     ['consistency','harmony','responsibility'], False),
    ('小组课题意见不合时', 'interpersonal-relationship', S_UNDERGRAD, 'fc', 3,
     [('坚持方案争取说服', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('投票少数服从多数', {'mbti.J':2,'enneagram.type6':1,'gallup.consistency':1}),
      ('综合两方取折中', {'mbti.F':2,'enneagram.type9':1,'gallup.harmony':1}),
      ('让有经验的人定', {'mbti.S':1,'enneagram.type6':1,'gallup.relator':1})],
     ['command','consistency','harmony'], False),
    ('宿舍熄灯后有人打电话', 'interpersonal-relationship', S_UNDERGRAD, 'fc', 1,
     [('直接提醒小声点', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('戴耳塞忍忍', {'mbti.I':1,'enneagram.type9':2,'gallup.adaptability':1}),
      ('第二天委婉提', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('和其他室友一起提', {'mbti.E':1,'enneagram.type6':1,'gallup.relator':1})],
     ['command','adaptability','empathy'], False),
    ('新生报到第一天你会', 'interpersonal-relationship', S_UNDERGRAD, 'fc', 1,
     [('主动跟每个人打招呼', {'mbti.E':3,'enneagram.type7':1,'gallup.woo':1}),
      ('等别人来找你聊', {'mbti.I':2,'enneagram.type5':1,'gallup.relator':1}),
      ('只跟看起来好相处的聊', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('先观察再决定深交', {'mbti.N':2,'enneagram.type6':1,'gallup.deliberative':1})],
     ['woo','relator','empathy','deliberative'], False),
    ('同学考试成绩比你好很多', 'interpersonal-relationship', S_SENIOR+S_UNDERGRAD, 'fc', 2,
     [('向TA请教学习方法', {'mbti.T':2,'enneagram.type3':1,'gallup.learner':1}),
      ('暗下决心下次超过', {'mbti.J':2,'enneagram.type8':1,'gallup.competition':1}),
      ('无所谓各有所长', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1}),
      ('有点失落但为TA高兴', {'mbti.F':2,'enneagram.type2':1,'gallup.positivity':1})],
     ['learner','competition','adaptability'], False),
    # likert-4
    ('在班级里我很容易交到朋友', 'interpersonal-relationship', S_JUNIOR+S_SENIOR, 'lk', 1,
     {'mbti.E':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.woo':[0,1,2,3]},
     ['woo','positivity'], False),
    ('我更喜欢一对一聊天而不是群聊', 'interpersonal-relationship', S_ALL_STU, 'lk', 2,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.relator':[0,1,2,3]},
     ['relator','intellection'], False),
    ('我能察觉到同学的情绪变化', 'interpersonal-relationship', S_ALL_STU, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.empathy':[0,1,2,3]},
     ['empathy','individualization'], False),
    ('我在人群中会感到不自在', 'interpersonal-relationship', S_ALL_STU, 'lk', 2,
     {'mbti.I':[0,1,2,3],'enneagram.type4':[0,0,1,2],'gallup.relator':[0,1,2,3]},
     ['relator','deliberative'], True),
    ('我会主动帮助成绩差的同学', 'interpersonal-relationship', S_JUNIOR+S_SENIOR, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.developer':[0,1,2,3]},
     ['developer','empathy'], False),
    ('我容易相信别人说的话', 'interpersonal-relationship', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.empathy':[0,1,2,3]},
     ['empathy','harmony'], False),
    ('我经常在群里发言活跃气氛', 'interpersonal-relationship', S_JUNIOR+S_SENIOR, 'lk', 1,
     {'mbti.E':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.communication':[0,1,2,3]},
     ['communication','positivity'], False),
    ('我会为了维持关系而委屈自己', 'interpersonal-relationship', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'enneagram.type9':[0,1,2,3]},
     ['harmony','empathy'], True),
    ('我宁愿一个人吃饭也不想去社交', 'interpersonal-relationship', S_ALL_STU, 'lk', 2,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','intellection'], False),
    ('我觉得真正的朋友不需要多', 'interpersonal-relationship', S_ALL_STU, 'lk', 3,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.relator':[0,1,2,3]},
     ['relator','individualization'], False),
    ('被老师当众批评我会很难过', 'interpersonal-relationship', S_JUNIOR+S_SENIOR, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type4':[0,0,1,2],'gallup.empathy':[0,1,2,3]},
     ['empathy','harmony'], True),
    ('我觉得合作比竞争更重要', 'interpersonal-relationship', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','developer'], False),
]

# ===== learning-cognition (24题) =====
NEW_QUESTIONS += [
    ('期末复习时你的策略是', 'learning-cognition', S_SENIOR+S_UNDERGRAD, 'fc', 2,
     [('提前两周系统复习', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('考前几天突击重点', {'mbti.P':2,'enneagram.type7':1,'gallup.activator':1}),
      ('跟同学组队互考', {'mbti.E':2,'enneagram.type3':1,'gallup.relator':1}),
      ('反复看错题本', {'mbti.S':2,'enneagram.type6':1,'gallup.restorative':1})],
     ['discipline','activator','relator'], False),
    ('面对数学难题你会', 'learning-cognition', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('先自己想半小时再问', {'mbti.T':2,'enneagram.type5':2,'gallup.intellection':1}),
      ('直接看答案理解思路', {'mbti.S':1,'enneagram.type6':1,'gallup.input':1}),
      ('问同学或老师', {'mbti.E':2,'enneagram.type2':1,'gallup.communication':1}),
      ('先做别的回头再看', {'mbti.P':1,'enneagram.type7':1,'gallup.adaptability':1})],
     ['intellection','input','communication'], False),
    ('选择选修课你最看重', 'learning-cognition', S_UNDERGRAD, 'fc', 3,
     [('对将来就业有用', {'mbti.T':2,'enneagram.type3':2,'gallup.futuristic':1}),
      ('自己感兴趣', {'mbti.F':2,'enneagram.type4':1,'gallup.learner':1}),
      ('老师给分高', {'mbti.S':1,'enneagram.type6':1,'gallup.maximizer':1}),
      ('同学推荐的', {'mbti.E':1,'enneagram.type9':1,'gallup.relator':1})],
     ['futuristic','learner','maximizer'], False),
    ('考试没考好你的第一反应', 'learning-cognition', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('分析错题找原因', {'mbti.T':2,'enneagram.type1':1,'gallup.analytical':1}),
      ('难过一阵然后振作', {'mbti.F':2,'enneagram.type4':1,'gallup.restorative':1}),
      ('觉得下次运气会好', {'mbti.P':1,'enneagram.type7':1,'gallup.positivity':1}),
      ('跟父母说寻求安慰', {'mbti.E':1,'enneagram.type2':1,'gallup.relator':1})],
     ['analytical','positivity','relator'], False),
    ('学英语时你更喜欢', 'learning-cognition', S_ALL_STU, 'fc', 2,
     [('背单词刷题', {'mbti.S':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('看美剧听英文歌', {'mbti.P':2,'enneagram.type7':1,'gallup.input':1}),
      ('找人用英语对话', {'mbti.E':2,'enneagram.type3':1,'gallup.communication':1}),
      ('读英文原著', {'mbti.N':2,'enneagram.type5':1,'gallup.intellection':1})],
     ['discipline','input','communication'], False),
    ('面对选科你会', 'learning-cognition', S_SENIOR, 'fc', 4,
     [('选成绩最好的', {'mbti.T':2,'enneagram.type3':2,'gallup.maximizer':1}),
      ('选最感兴趣的', {'mbti.F':2,'enneagram.type4':1,'gallup.learner':1}),
      ('选就业前景最好的', {'mbti.N':2,'enneagram.type3':1,'gallup.futuristic':1}),
      ('听父母老师建议', {'mbti.S':1,'enneagram.type6':2,'gallup.relator':1})],
     ['maximizer','learner','futuristic'], False),
    ('你觉得最有效的记忆方法', 'learning-cognition', S_ALL_STU, 'fc', 3,
     [('反复背诵', {'mbti.S':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('理解后自然记住', {'mbti.N':2,'enneagram.type5':2,'gallup.intellection':1}),
      ('讲给别人听', {'mbti.E':2,'enneagram.type3':1,'gallup.communication':1}),
      ('做题在应用中记', {'mbti.T':2,'enneagram.type8':1,'gallup.activator':1})],
     ['discipline','intellection','communication'], False),
    ('老师在课堂上讲错了你会', 'learning-cognition', S_SENIOR+S_UNDERGRAD, 'fc', 3,
     [('举手当场指出', {'mbti.T':2,'enneagram.type1':2,'gallup.command':1}),
      ('下课后私下告诉', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('跟同学讨论确认再说', {'mbti.N':1,'enneagram.type6':1,'gallup.analytical':1}),
      ('算了不影响大局', {'mbti.P':1,'enneagram.type9':2,'gallup.harmony':1})],
     ['command','empathy','analytical'], False),
    ('你更喜欢的课堂形式是', 'learning-cognition', S_ALL_STU, 'fc', 2,
     [('老师讲我听', {'mbti.S':2,'enneagram.type6':1,'gallup.input':1}),
      ('小组讨论', {'mbti.E':2,'enneagram.type7':1,'gallup.communication':1}),
      ('动手实验实践', {'holland.R':3,'mbti.S':1,'gallup.activator':1}),
      ('自学然后做题', {'mbti.I':2,'enneagram.type5':1,'gallup.learner':1})],
     ['input','communication','activator'], False),
    ('假期你会怎么安排学习', 'learning-cognition', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('制定详细计划严格执行', {'mbti.J':3,'enneagram.type1':1,'gallup.discipline':1}),
      ('有大方向灵活调整', {'mbti.P':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('报补习班跟着学', {'mbti.S':1,'enneagram.type6':1,'gallup.relator':1}),
      ('看心情想学就学', {'mbti.P':1,'enneagram.type4':1,'gallup.positivity':1})],
     ['discipline','adaptability','relator'], False),
    ('做小组课题你通常负责', 'learning-cognition', S_UNDERGRAD, 'fc', 2,
     [('统筹分工和进度', {'mbti.J':2,'enneagram.type8':1,'gallup.arranger':1}),
      ('查资料写报告', {'mbti.I':2,'enneagram.type5':1,'gallup.input':1}),
      ('做PPT和展示', {'mbti.E':2,'enneagram.type3':1,'gallup.communication':1}),
      ('出创意和点子', {'mbti.N':2,'enneagram.type7':1,'gallup.ideation':1})],
     ['arranger','input','communication'], False),
    ('在图书馆旁边有人说话', 'learning-cognition', S_ALL_STU, 'fc', 1,
     [('换个位置', {'mbti.I':1,'enneagram.type9':1,'gallup.adaptability':1}),
      ('提醒他们安静', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('戴耳机继续学', {'mbti.P':1,'enneagram.type5':1,'gallup.focus':1}),
      ('告诉管理员', {'mbti.J':1,'enneagram.type1':1,'gallup.responsibility':1})],
     ['adaptability','command','focus'], False),
    ('考研/保研选校你最看重', 'learning-cognition', S_GRAD, 'fc', 4,
     [('学校排名和名气', {'mbti.T':2,'enneagram.type3':2,'gallup.significance':1}),
      ('导师的研究方向', {'mbti.N':2,'enneagram.type5':2,'gallup.learner':1}),
      ('城市的就业机会', {'mbti.S':1,'enneagram.type6':1,'gallup.futuristic':1}),
      ('录取难度和成功率', {'mbti.T':1,'enneagram.type6':1,'gallup.deliberative':1})],
     ['significance','learner','futuristic'], False),
    ('面对留学语言考试你会', 'learning-cognition', S_UNDERGRAD, 'fc', 4,
     [('报班系统学习', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('自学刷题备考', {'mbti.I':2,'enneagram.type5':1,'gallup.learner':1}),
      ('找语伴练习口语', {'mbti.E':2,'enneagram.type3':1,'gallup.communication':1}),
      ('先看经验贴再定计划', {'mbti.N':1,'enneagram.type6':1,'gallup.input':1})],
     ['discipline','learner','communication'], False),
    ('参加学科竞赛你会', 'learning-cognition', S_SENIOR+S_UNDERGRAD, 'fc', 3,
     [('全力以赴争名次', {'mbti.T':2,'enneagram.type3':2,'gallup.competition':1}),
      ('享受过程不在乎结果', {'mbti.P':2,'enneagram.type7':1,'gallup.positivity':1}),
      ('组队参加发挥各自优势', {'mbti.E':2,'enneagram.type2':1,'gallup.arranger':1}),
      ('不参加没兴趣', {'mbti.I':1,'enneagram.type4':1,'gallup.deliberative':1})],
     ['competition','positivity','arranger'], False),
    # likert-4
    ('我喜欢动手做实验胜过看书', 'learning-cognition', S_ALL_STU, 'lk', 2,
     {'holland.R':[0,1,2,3],'mbti.S':[0,1,2,3],'gallup.activator':[0,0,1,2]},
     ['activator','context'], False),
    ('我习惯用思维导图整理知识', 'learning-cognition', S_ALL_STU, 'lk', 3,
     {'mbti.N':[0,1,2,3],'gallup.strategic':[0,1,2,3],'gallup.ideation':[0,0,1,2]},
     ['strategic','ideation'], False),
    ('我更喜欢一个人安静地学习', 'learning-cognition', S_ALL_STU, 'lk', 1,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.focus':[0,1,2,3]},
     ['focus','intellection'], False),
    ('我能长时间专注于一道题', 'learning-cognition', S_ALL_STU, 'lk', 3,
     {'mbti.I':[0,1,2,3],'gallup.focus':[0,1,2,3],'gallup.deliberative':[0,0,1,2]},
     ['focus','deliberative'], False),
    ('我对新知识总是充满好奇', 'learning-cognition', S_ALL_STU, 'lk', 1,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.learner':[0,1,2,3]},
     ['learner','ideation'], False),
    ('我觉得实践比理论更重要', 'learning-cognition', S_ALL_STU, 'lk', 3,
     {'holland.R':[0,1,2,3],'mbti.S':[0,1,2,3],'gallup.activator':[0,0,1,2]},
     ['activator','context'], False),
    ('我会主动预习下节课的内容', 'learning-cognition', S_JUNIOR+S_SENIOR, 'lk', 2,
     {'mbti.J':[0,1,2,3],'gallup.discipline':[0,1,2,3],'gallup.achiever':[0,0,1,2]},
     ['discipline','achiever'], False),
    ('我能从失败中快速总结教训', 'learning-cognition', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'gallup.restorative':[0,1,2,3],'enneagram.type1':[0,0,1,2]},
     ['restorative','analytical'], False),
    ('我觉得记忆比理解更重要', 'learning-cognition', S_ALL_STU, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.input':[0,1,2,3]},
     ['input','discipline'], True),
]

print(f'前2类完成: {len(NEW_QUESTIONS)} 题')
# 继续写入剩余类别...
# 为了控制脚本长度，剩余8类用更紧凑的模板生成

# ===== stress-response (24题) =====
NEW_QUESTIONS += [
    ('考试前一晚你通常', 'stress-response', S_JUNIOR+S_SENIOR, 'fc', 1,
     [('正常睡觉养精蓄锐', {'mbti.J':2,'enneagram.type9':1,'gallup.discipline':1}),
      ('再刷几套题才安心', {'mbti.T':2,'enneagram.type1':1,'gallup.achiever':1}),
      ('紧张得睡不着', {'mbti.F':2,'enneagram.type4':1,'gallup.deliberative':1}),
      ('放松看电视转移注意力', {'mbti.P':1,'enneagram.type7':1,'gallup.positivity':1})],
     ['discipline','achiever','positivity'], False),
    ('老师突击检查作业你没写完', 'stress-response', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('老实承认接受批评', {'mbti.T':2,'enneagram.type1':2,'gallup.responsibility':1}),
      ('找借口搪塞过去', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1}),
      ('赶紧抄同学的补上', {'mbti.P':2,'enneagram.type3':1,'gallup.activator':1}),
      ('课后主动找老师补交', {'mbti.J':2,'enneagram.type6':1,'gallup.responsibility':1})],
     ['responsibility','adaptability','activator'], False),
    ('面对高考/中考你感觉', 'stress-response', S_SENIOR, 'fc', 4,
     [('紧张但充满斗志', {'mbti.T':2,'enneagram.type3':2,'gallup.achiever':1}),
      ('压力很大常失眠', {'mbti.F':2,'enneagram.type4':2,'gallup.deliberative':1}),
      ('平常心尽力就好', {'mbti.P':2,'enneagram.type9':1,'gallup.positivity':1}),
      ('既期待又害怕', {'mbti.N':2,'enneagram.type6':1,'gallup.futuristic':1})],
     ['achiever','deliberative','positivity'], False),
    ('连续几门考试砸了你', 'stress-response', S_SENIOR+S_UNDERGRAD, 'fc', 3,
     [('分析原因调整方法', {'mbti.T':2,'enneagram.type1':1,'gallup.restorative':1}),
      ('找人倾诉释放压力', {'mbti.E':2,'enneagram.type2':1,'gallup.relator':1}),
      ('先玩几天再说', {'mbti.P':2,'enneagram.type7':2,'gallup.positivity':1}),
      ('更加努力证明自己', {'mbti.J':2,'enneagram.type8':1,'gallup.achiever':1})],
     ['restorative','relator','positivity','achiever'], False),
    ('论文/作业截止前一天', 'stress-response', S_UNDERGRAD+S_GRAD, 'fc', 2,
     [('早就写完了检查一遍', {'mbti.J':3,'enneagram.type1':1,'gallup.discipline':1}),
      ('还有一半熬夜赶', {'mbti.P':2,'enneagram.type7':1,'gallup.activator':1}),
      ('刚开始写通宵搞定', {'mbti.P':3,'enneagram.type4':1,'gallup.activator':1}),
      ('提前申请延期', {'mbti.T':1,'enneagram.type6':1,'gallup.deliberative':1})],
     ['discipline','activator','deliberative'], False),
    ('你在考场上遇到不会的题', 'stress-response', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('跳过先做会的', {'mbti.T':2,'enneagram.type5':1,'gallup.strategic':1}),
      ('死磕直到想出来', {'mbti.J':2,'enneagram.type1':2,'gallup.focus':1}),
      ('随便蒙一个', {'mbti.P':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('越想越慌影响后面', {'mbti.F':2,'enneagram.type4':1,'gallup.deliberative':1})],
     ['strategic','focus','adaptability'], False),
    ('父母对你期望很高你感到', 'stress-response', S_JUNIOR+S_SENIOR, 'fc', 3,
     [('压力大但会努力', {'mbti.J':2,'enneagram.type1':1,'gallup.achiever':1}),
      ('想让他们满意但怕做不到', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('有沟通让他们理解我', {'mbti.E':2,'enneagram.type3':1,'gallup.communication':1}),
      ('无所谓做好自己就行', {'mbti.P':1,'enneagram.type5':1,'gallup.self_assurance':1})],
     ['achiever','empathy','communication'], False),
    ('被老师叫去办公室谈话你', 'stress-response', S_JUNIOR+S_SENIOR, 'fc', 2,
     [('紧张想是不是犯错了', {'mbti.F':2,'enneagram.type6':2,'gallup.deliberative':1}),
      ('淡定面对该咋咋', {'mbti.T':2,'enneagram.type8':1,'gallup.self_assurance':1}),
      ('好奇老师要说什么', {'mbti.N':2,'enneagram.type7':1,'gallup.positivity':1}),
      ('先想好怎么应对', {'mbti.J':2,'enneagram.type1':1,'gallup.strategic':1})],
     ['deliberative','self_assurance','positivity'], False),
    # likert-4
    ('作业太多时我会焦虑', 'stress-response', S_JUNIOR+S_SENIOR, 'lk', 1,
     {'enneagram.type4':[0,1,2,3],'gallup.deliberative':[0,0,1,2],'mbti.F':[0,1,2,3]},
     ['deliberative','restorative'], True),
    ('我能很好调节考试压力', 'stress-response', S_ALL_STU, 'lk', 2,
     {'gallup.adaptability':[0,1,2,3],'enneagram.type9':[0,0,1,2],'mbti.P':[0,1,2,3]},
     ['adaptability','positivity'], False),
    ('排名下降我会很沮丧', 'stress-response', S_SENIOR, 'lk', 2,
     {'enneagram.type3':[0,1,2,3],'gallup.significance':[0,0,1,2],'mbti.F':[0,1,2,3]},
     ['significance','achiever'], True),
    ('我容易因为成绩影响心情', 'stress-response', S_JUNIOR+S_SENIOR, 'lk', 2,
     {'enneagram.type4':[0,1,2,3],'mbti.F':[0,1,2,3],'gallup.empathy':[0,0,1,2]},
     ['empathy','restorative'], True),
    ('面对deadline我效率反而更高', 'stress-response', S_UNDERGRAD+S_GRAD, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.activator':[0,1,2,3]},
     ['activator','focus'], False),
    ('我会反复检查是否带齐考试用品', 'stress-response', S_JUNIOR+S_SENIOR, 'lk', 1,
     {'mbti.J':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','discipline'], False),
    ('面对压力我会选择运动发泄', 'stress-response', S_ALL_STU, 'lk', 2,
     {'holland.R':[0,1,2,3],'gallup.activator':[0,0,1,2],'mbti.S':[0,1,2,3]},
     ['activator','positivity'], False),
    ('我害怕在全班面前回答问题', 'stress-response', S_JUNIOR+S_SENIOR, 'lk', 2,
     {'mbti.I':[0,1,2,3],'enneagram.type4':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','relator'], True),
    ('我会因为担心结果而无法开始', 'stress-response', S_ALL_STU, 'lk', 3,
     {'enneagram.type6':[0,1,2,3],'gallup.deliberative':[0,1,2,3],'mbti.F':[0,0,1,2]},
     ['deliberative','analytical'], True),
    ('考研备考期间我会感到孤独', 'stress-response', S_GRAD, 'lk', 3,
     {'mbti.I':[0,1,2,3],'enneagram.type4':[0,0,1,2],'gallup.relator':[0,1,2,3]},
     ['relator','empathy'], True),
    ('我觉得压力能激发我的潜能', 'stress-response', S_ALL_STU, 'lk', 3,
     {'enneagram.type3':[0,1,2,3],'gallup.achiever':[0,1,2,3],'mbti.T':[0,0,1,2]},
     ['achiever','significance'], False),
    ('面试/答辩前我会反复练习', 'stress-response', S_UNDERGRAD+S_GRAD, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.discipline':[0,1,2,3]},
     ['discipline','focus'], False),
    ('我觉得失败是很丢人的事', 'stress-response', S_ALL_STU, 'lk', 4,
     {'enneagram.type3':[0,1,2,3],'gallup.significance':[0,0,1,2],'mbti.F':[0,1,2,3]},
     ['significance','achiever'], True),
    ('我习惯把压力憋在心里', 'stress-response', S_ALL_STU, 'lk', 3,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','intellection'], True),
    ('面对不确定的结果我会很焦虑', 'stress-response', S_ALL_STU, 'lk', 3,
     {'enneagram.type6':[0,1,2,3],'gallup.deliberative':[0,1,2,3],'mbti.J':[0,0,1,2]},
     ['deliberative','discipline'], True),
    ('我觉得请假/逃课是不负责任', 'stress-response', S_ALL_STU, 'lk', 3,
     {'enneagram.type1':[0,1,2,3],'gallup.responsibility':[0,1,2,3],'mbti.J':[0,0,1,2]},
     ['responsibility','discipline'], False),
]

print(f'前4类完成: {len(NEW_QUESTIONS)} 题')

# ===== motivation-value (24题) =====
NEW_QUESTIONS += [
    ('你选择大学专业最看重', 'motivation-value', S_SENIOR+S_UNDERGRAD, 'fc', 4,
     [('兴趣和热爱', {'mbti.F':3,'enneagram.type4':1,'gallup.learner':1}),
      ('就业前景和薪资', {'mbti.T':2,'enneagram.type3':2,'gallup.futuristic':1}),
      ('社会价值和意义', {'mbti.N':2,'enneagram.type2':1,'gallup.belief':1}),
      ('家人期望', {'mbti.S':1,'enneagram.type6':1,'gallup.harmony':1})],
     ['learner','futuristic','belief'], False),
    ('你觉得学习的意义是', 'motivation-value', S_ALL_STU, 'fc', 3,
     [('考上好学校找好工作', {'mbti.T':2,'enneagram.type3':2,'gallup.achiever':1}),
      ('探索世界满足好奇心', {'mbti.N':2,'enneagram.type7':1,'gallup.learner':1}),
      ('成为更好的自己', {'mbti.F':2,'enneagram.type1':1,'gallup.maximizer':1}),
      ('让父母骄傲', {'mbti.S':1,'enneagram.type2':1,'gallup.responsibility':1})],
     ['achiever','learner','maximizer'], False),
    ('如果不用考虑分数你会选', 'motivation-value', S_ALL_STU, 'fc', 3,
     [('最喜欢的科目深入研究', {'mbti.N':2,'enneagram.type5':2,'gallup.learner':1}),
      ('最实用的技能学习', {'mbti.T':2,'enneagram.type3':1,'gallup.futuristic':1}),
      ('艺术体育等兴趣课', {'holland.A':2,'mbti.F':1,'gallup.positivity':1}),
      ('什么都不想学了', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['learner','futuristic','positivity'], False),
    ('你理想中的老师是', 'motivation-value', S_ALL_STU, 'fc', 2,
     [('知识渊博能解答一切', {'mbti.N':2,'enneagram.type5':1,'gallup.input':1}),
      ('关心学生像朋友一样', {'mbti.F':2,'enneagram.type2':1,'gallup.developer':1}),
      ('严格要求高效果好', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('幽默风趣课堂有趣', {'mbti.E':2,'enneagram.type7':1,'gallup.communication':1})],
     ['input','developer','discipline','communication'], False),
    ('你选择社团最看重', 'motivation-value', S_UNDERGRAD, 'fc', 2,
     [('能学到实用技能', {'mbti.T':2,'enneagram.type3':1,'gallup.learner':1}),
      ('能交到好朋友', {'mbti.F':2,'enneagram.type2':1,'gallup.relator':1}),
      ('对简历有帮助', {'mbti.J':2,'enneagram.type3':2,'gallup.significance':1}),
      ('纯粹感兴趣', {'mbti.P':1,'enneagram.type7':1,'gallup.positivity':1})],
     ['learner','relator','significance'], False),
    ('你选择读研的最主要原因', 'motivation-value', S_GRAD, 'fc', 4,
     [('热爱学术想深入研究', {'mbti.N':2,'enneagram.type5':2,'gallup.learner':1}),
      ('提升学历增加竞争力', {'mbti.T':2,'enneagram.type3':2,'gallup.achiever':1}),
      ('还没想好做什么', {'mbti.P':1,'enneagram.type6':1,'gallup.deliberative':1}),
      ('家里要求', {'mbti.S':1,'enneagram.type6':1,'gallup.harmony':1})],
     ['learner','achiever','deliberative'], False),
    ('如果获得一笔奖学金你会', 'motivation-value', S_ALL_STU, 'fc', 2,
     [('买学习资料/课程', {'mbti.J':2,'enneagram.type1':1,'gallup.learner':1}),
      ('存起来以后用', {'mbti.T':2,'enneagram.type6':1,'gallup.deliberative':1}),
      ('请朋友庆祝一下', {'mbti.E':2,'enneagram.type7':1,'gallup.positivity':1}),
      ('买一直想要的东西', {'mbti.F':1,'enneagram.type4':1,'gallup.significance':1})],
     ['learner','deliberative','positivity'], False),
    ('你最不能接受哪种学习方式', 'motivation-value', S_ALL_STU, 'fc', 3,
     [('死记硬背不理解', {'mbti.N':2,'enneagram.type5':1,'gallup.intellection':1}),
      ('纯听课不做练习', {'mbti.S':2,'enneagram.type1':1,'gallup.activator':1}),
      ('一个人闷头学', {'mbti.E':2,'enneagram.type7':1,'gallup.communication':1}),
      ('没有目标的散漫学习', {'mbti.J':2,'enneagram.type3':1,'gallup.focus':1})],
     ['intellection','activator','communication'], False),
    # likert-4
    ('我觉得学历比能力重要', 'motivation-value', S_ALL_STU, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.significance':[0,1,2,3]},
     ['significance','achiever'], True),
    ('我更在意过程而不是结果', 'motivation-value', S_ALL_STU, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.positivity':[0,1,2,3]},
     ['positivity','adaptability'], False),
    ('我选择专业时会考虑家庭意见', 'motivation-value', S_SENIOR+S_UNDERGRAD, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','relator'], False),
    ('我觉得做喜欢的事不怕辛苦', 'motivation-value', S_ALL_STU, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.learner':[0,1,2,3]},
     ['learner','positivity'], False),
    ('我希望将来能改变某个领域', 'motivation-value', S_ALL_STU, 'lk', 4,
     {'mbti.N':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.significance':[0,1,2,3]},
     ['significance','futuristic'], False),
    ('我觉得稳定比高薪更重要', 'motivation-value', S_ALL_STU, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.consistency':[0,1,2,3]},
     ['consistency','deliberative'], False),
    ('我愿意为梦想放弃安稳', 'motivation-value', S_ALL_STU, 'lk', 4,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','self_assurance'], False),
    ('我觉得赚钱是学习的首要目的', 'motivation-value', S_ALL_STU, 'lk', 4,
     {'mbti.T':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.achiever':[0,1,2,3]},
     ['achiever','significance'], True),
    ('我觉得帮助他人比成就自己更重要', 'motivation-value', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.developer':[0,1,2,3]},
     ['developer','empathy'], False),
    ('我会为了GPA牺牲兴趣爱好', 'motivation-value', S_UNDERGRAD, 'lk', 3,
     {'mbti.J':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.achiever':[0,1,2,3]},
     ['achiever','discipline'], True),
    ('我觉得出国留学能开阔眼界', 'motivation-value', S_UNDERGRAD+S_GRAD, 'lk', 2,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','learner'], False),
    ('我更在意别人的评价而不是自己的', 'motivation-value', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'enneagram.type3':[0,1,2,3]},
     ['significance','empathy'], True),
    ('我觉得第一份工作最重要的是学习', 'motivation-value', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.N':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.learner':[0,1,2,3]},
     ['learner','input'], False),
    ('我愿意尝试完全陌生的领域', 'motivation-value', S_ALL_STU, 'lk', 3,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','learner'], False),
    ('我觉得实习经历比上课重要', 'motivation-value', S_UNDERGRAD+S_GRAD, 'lk', 3,
     {'holland.R':[0,1,2,3],'mbti.S':[0,0,1,2],'gallup.activator':[0,1,2,3]},
     ['activator','context'], False),
    ('我选择工作会考虑社会价值', 'motivation-value', S_GRAD+S_CAREER, 'lk', 4,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.belief':[0,1,2,3]},
     ['belief','developer'], False),
]

print(f'前6类完成: {len(NEW_QUESTIONS)} 题')

# ===== emotion-self (24题) =====
NEW_QUESTIONS += [
    ('你在陌生环境中通常', 'emotion-self', S_ALL_STU, 'fc', 1,
     [('很快能适应', {'mbti.E':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('需要一段时间', {'mbti.I':2,'enneagram.type6':1,'gallup.deliberative':1}),
      ('会感到焦虑不安', {'mbti.F':2,'enneagram.type4':1,'gallup.empathy':1}),
      ('先观察再融入', {'mbti.N':2,'enneagram.type5':1,'gallup.intellection':1})],
     ['adaptability','deliberative','empathy'], False),
    ('取得成绩后你更倾向', 'emotion-self', S_ALL_STU, 'fc', 2,
     [('跟好朋友分享', {'mbti.E':2,'enneagram.type7':1,'gallup.communication':1}),
      ('自己开心就好', {'mbti.I':2,'enneagram.type5':1,'gallup.self_assurance':1}),
      ('发朋友圈记录', {'mbti.E':1,'enneagram.type3':1,'gallup.significance':1}),
      ('马上想下一个目标', {'mbti.J':2,'enneagram.type3':2,'gallup.achiever':1})],
     ['communication','self_assurance','significance'], False),
    ('你觉得自己最大的优点是', 'emotion-self', S_ALL_STU, 'fc', 3,
     [('坚持不放弃', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('善于理解别人', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('学习能力强', {'mbti.N':2,'enneagram.type5':1,'gallup.learner':1}),
      ('人缘好朋友多', {'mbti.E':2,'enneagram.type7':1,'gallup.woo':1})],
     ['discipline','empathy','learner','woo'], False),
    ('当你感到迷茫时你会', 'emotion-self', S_ALL_STU, 'fc', 3,
     [('找人倾诉', {'mbti.E':2,'enneagram.type2':1,'gallup.relator':1}),
      ('一个人静静想想', {'mbti.I':2,'enneagram.type5':1,'gallup.intellection':1}),
      ('运动或做喜欢的事', {'holland.R':2,'mbti.S':1,'gallup.activator':1}),
      ('写日记或记录心情', {'mbti.F':2,'enneagram.type4':1,'gallup.input':1})],
     ['relator','intellection','activator'], False),
    ('你对未来的大学生活', 'emotion-self', S_SENIOR, 'fc', 2,
     [('充满期待', {'mbti.E':2,'enneagram.type7':2,'gallup.positivity':1}),
      ('有点紧张担心', {'mbti.F':2,'enneagram.type6':1,'gallup.deliberative':1}),
      ('既期待又紧张', {'mbti.N':2,'enneagram.type6':1,'gallup.futuristic':1}),
      ('没特别感觉', {'mbti.T':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['positivity','deliberative','futuristic'], False),
    ('面对不喜欢的课你会', 'emotion-self', S_ALL_STU, 'fc', 2,
     [('强迫自己认真听', {'mbti.J':2,'enneagram.type1':2,'gallup.discipline':1}),
      ('做自己的事', {'mbti.P':2,'enneagram.type4':1,'gallup.adaptability':1}),
      ('试着找到有趣的点', {'mbti.N':2,'enneagram.type7':1,'gallup.learner':1}),
      ('能逃就逃', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['discipline','adaptability','learner'], False),
    ('周末没有作业时你通常', 'emotion-self', S_JUNIOR+S_SENIOR, 'fc', 1,
     [('出门跟朋友玩', {'mbti.E':2,'enneagram.type7':2,'gallup.woo':1}),
      ('在家看书或追剧', {'mbti.I':2,'enneagram.type5':1,'gallup.input':1}),
      ('运动或户外活动', {'holland.R':3,'mbti.S':1,'gallup.activator':1}),
      ('提前学下周内容', {'mbti.J':2,'enneagram.type1':1,'gallup.achiever':1})],
     ['woo','input','activator','achiever'], False),
    ('你觉得自己最需要改进的是', 'emotion-self', S_ALL_STU, 'fc', 3,
     [('太拖延', {'mbti.P':2,'enneagram.type9':1,'gallup.discipline':1}),
      ('不够自信', {'mbti.I':2,'enneagram.type4':1,'gallup.self_assurance':1}),
      ('容易焦虑', {'mbti.F':2,'enneagram.type6':1,'gallup.adaptability':1}),
      ('不会拒绝别人', {'mbti.F':1,'enneagram.type2':2,'gallup.harmony':1})],
     ['discipline','self_assurance','adaptability'], False),
    # likert-4
    ('我对自己的外貌感到满意', 'emotion-self', S_ALL_STU, 'lk', 2,
     {'gallup.self_assurance':[0,1,2,3],'enneagram.type3':[0,0,1,2],'mbti.E':[0,0,1,2]},
     ['self_assurance','positivity'], False),
    ('我经常反思自己的行为', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'mbti.I':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.intellection':[0,1,2,3]},
     ['intellection','deliberative'], False),
    ('我觉得自己的情绪很稳定', 'emotion-self', S_ALL_STU, 'lk', 2,
     {'enneagram.type9':[0,1,2,3],'gallup.adaptability':[0,1,2,3],'mbti.T':[0,0,1,2]},
     ['adaptability','harmony'], False),
    ('我会因为别人的一句话想很多', 'emotion-self', S_ALL_STU, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type4':[0,0,1,2],'gallup.empathy':[0,1,2,3]},
     ['empathy','deliberative'], True),
    ('我清楚自己想要什么', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'mbti.J':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.focus':[0,1,2,3]},
     ['focus','self_assurance'], False),
    ('离开家上学我会很想家', 'emotion-self', S_UNDERGRAD, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.relator':[0,1,2,3]},
     ['relator','connectedness'], False),
    ('我习惯把情绪藏起来', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','intellection'], True),
    ('我觉得自己比同龄人成熟', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.responsibility':[0,1,2,3]},
     ['responsibility','self_assurance'], False),
    ('我会因为别人比我优秀而自卑', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'enneagram.type4':[0,1,2,3],'mbti.F':[0,0,1,2],'gallup.significance':[0,1,2,3]},
     ['significance','empathy'], True),
    ('我觉得一个人也可以很充实', 'emotion-self', S_ALL_STU, 'lk', 2,
     {'mbti.I':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.self_assurance':[0,1,2,3]},
     ['self_assurance','intellection'], False),
    ('我经常感到孤独', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'mbti.I':[0,1,2,3],'enneagram.type4':[0,0,1,2],'gallup.relator':[0,1,2,3]},
     ['relator','empathy'], True),
    ('我对自己的学习能力有信心', 'emotion-self', S_ALL_STU, 'lk', 2,
     {'gallup.self_assurance':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.learner':[0,1,2,3]},
     ['self_assurance','learner'], False),
    ('我会因为考试成绩否定自己', 'emotion-self', S_JUNIOR+S_SENIOR, 'lk', 3,
     {'enneagram.type3':[0,1,2,3],'mbti.F':[0,0,1,2],'gallup.significance':[0,1,2,3]},
     ['significance','achiever'], True),
    ('我觉得表达情绪是软弱的表现', 'emotion-self', S_ALL_STU, 'lk', 4,
     {'mbti.T':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.self_assurance':[0,1,2,3]},
     ['self_assurance','command'], True),
    ('我能接受自己的不完美', 'emotion-self', S_ALL_STU, 'lk', 3,
     {'enneagram.type9':[0,1,2,3],'gallup.adaptability':[0,1,2,3],'mbti.F':[0,0,1,2]},
     ['adaptability','positivity'], False),
    ('我觉得未来充满可能性', 'emotion-self', S_ALL_STU, 'lk', 2,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','positivity'], False),
]

print(f'前8类完成: {len(NEW_QUESTIONS)} 题')

# ===== action-habit (24题) =====
NEW_QUESTIONS += [
    ('你的书桌通常', 'action-habit', S_ALL_STU, 'fc', 1,
     [('整整齐齐分类放好', {'mbti.J':2,'enneagram.type1':2,'gallup.discipline':1}),
      ('有点乱但能找到', {'mbti.P':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('用完就收', {'mbti.J':1,'enneagram.type6':1,'gallup.responsibility':1}),
      ('堆满了再说', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['discipline','adaptability','responsibility'], False),
    ('你每天玩手机的时间', 'action-habit', S_ALL_STU, 'fc', 2,
     [('不到1小时自控力强', {'mbti.J':3,'enneagram.type1':1,'gallup.discipline':1}),
      ('1-3小时适度娱乐', {'mbti.P':2,'enneagram.type9':1,'gallup.adaptability':1}),
      ('3-5小时有点沉迷', {'mbti.P':1,'enneagram.type7':1,'gallup.adaptability':1}),
      ('没算过随心情', {'mbti.P':1,'enneagram.type4':1,'gallup.positivity':1})],
     ['discipline','adaptability','positivity'], False),
    ('你做笔记的习惯是', 'action-habit', S_ALL_STU, 'fc', 2,
     [('工整详细用多种颜色', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('只记关键词', {'mbti.N':2,'enneagram.type5':1,'gallup.strategic':1}),
      ('拍照课后整理', {'mbti.S':1,'enneagram.type6':1,'gallup.input':1}),
      ('不太做笔记', {'mbti.P':1,'enneagram.type7':1,'gallup.adaptability':1})],
     ['discipline','strategic','input'], False),
    ('制定学习计划后你', 'action-habit', S_ALL_STU, 'fc', 2,
     [('严格执行不打折扣', {'mbti.J':3,'enneagram.type1':1,'gallup.discipline':1}),
      ('大致执行偶尔调整', {'mbti.J':1,'enneagram.type3':1,'gallup.focus':1}),
      ('执行几天就放弃', {'mbti.P':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('从不定计划', {'mbti.P':2,'enneagram.type9':1,'gallup.adaptability':1})],
     ['discipline','focus','adaptability'], False),
    ('你更喜欢哪种运动方式', 'action-habit', S_ALL_STU, 'fc', 2,
     [('团队运动如篮球足球', {'mbti.E':2,'holland.S':1,'gallup.relator':1}),
      ('个人运动如跑步游泳', {'mbti.I':2,'holland.R':2,'gallup.focus':1}),
      ('健身房举铁', {'holland.R':3,'mbti.T':1,'gallup.achiever':1}),
      ('不太运动', {'mbti.I':1,'enneagram.type5':1,'gallup.intellection':1})],
     ['relator','focus','achiever'], False),
    ('面对手工作业/实验课你', 'action-habit', S_ALL_STU, 'fc', 2,
     [('特别喜欢动手能力强', {'holland.R':3,'mbti.S':1,'gallup.activator':1}),
      ('能完成但不算擅长', {'mbti.S':2,'enneagram.type6':1,'gallup.adaptability':1}),
      ('更喜欢理论分析', {'mbti.N':2,'enneagram.type5':1,'gallup.intellection':1}),
      ('觉得麻烦不想做', {'mbti.P':1,'enneagram.type7':1,'gallup.positivity':1})],
     ['activator','adaptability','intellection'], False),
    ('你起床后第一件事通常', 'action-habit', S_ALL_STU, 'fc', 1,
     [('看手机', {'mbti.P':1,'enneagram.type7':1,'gallup.input':1}),
      ('洗漱整理', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('想想今天要做什么', {'mbti.J':2,'enneagram.type3':1,'gallup.focus':1}),
      ('赖床再躺会', {'mbti.P':1,'enneagram.type9':2,'gallup.adaptability':1})],
     ['input','discipline','focus'], False),
    ('你觉得自己的动手能力', 'action-habit', S_ALL_STU, 'fc', 2,
     [('很强喜欢修东西做手工', {'holland.R':3,'mbti.S':1,'gallup.activator':1}),
      ('还可以能应付日常', {'mbti.S':2,'enneagram.type6':1,'gallup.adaptability':1}),
      ('一般更擅长动脑', {'mbti.N':2,'enneagram.type5':1,'gallup.intellection':1}),
      ('比较差经常搞砸', {'mbti.P':1,'enneagram.type4':1,'gallup.deliberative':1})],
     ['activator','adaptability','intellection'], False),
    # likert-4
    ('我习惯提前完成任务', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'gallup.discipline':[0,1,2,3],'gallup.achiever':[0,0,1,2]},
     ['discipline','achiever'], False),
    ('我做事前喜欢先定计划', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.strategic':[0,1,2,3]},
     ['strategic','discipline'], False),
    ('我能坚持每天背单词/做题', 'action-habit', S_ALL_STU, 'lk', 3,
     {'mbti.J':[0,1,2,3],'gallup.discipline':[0,1,2,3],'enneagram.type1':[0,0,1,2]},
     ['discipline','focus'], False),
    ('我经常丢三落四', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], True),
    ('我喜欢把事情留到最后', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.activator':[0,1,2,3]},
     ['activator','adaptability'], True),
    ('我有记账/记录开支的习惯', 'action-habit', S_ALL_STU, 'lk', 3,
     {'mbti.J':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.discipline':[0,1,2,3]},
     ['discipline','deliberative'], False),
    ('我喜欢整洁有序的环境', 'action-habit', S_ALL_STU, 'lk', 1,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.discipline':[0,1,2,3]},
     ['discipline','consistency'], False),
    ('我会定期整理手机相册和文件', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'gallup.discipline':[0,1,2,3],'enneagram.type1':[0,0,1,2]},
     ['discipline','arranger'], False),
    ('我习惯边学习边吃东西', 'action-habit', S_ALL_STU, 'lk', 1,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], False),
    ('我更喜欢户外实践而不是坐在教室', 'action-habit', S_ALL_STU, 'lk', 2,
     {'holland.R':[0,1,2,3],'mbti.S':[0,0,1,2],'gallup.activator':[0,1,2,3]},
     ['activator','context'], False),
    ('我会用APP管理日程和任务', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'gallup.discipline':[0,1,2,3],'gallup.arranger':[0,0,1,2]},
     ['discipline','arranger'], False),
    ('我经常忘记回复消息', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.P':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], True),
    ('我擅长同时做多件事', 'action-habit', S_ALL_STU, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.arranger':[0,1,2,3]},
     ['arranger','adaptability'], False),
    ('我觉得守时非常重要', 'action-habit', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.responsibility':[0,1,2,3]},
     ['responsibility','discipline'], False),
    ('我会定期运动保持身体健康', 'action-habit', S_ALL_STU, 'lk', 2,
     {'holland.R':[0,1,2,3],'gallup.discipline':[0,0,1,2],'gallup.achiever':[0,1,2,3]},
     ['achiever','discipline'], False),
    ('我做事三分钟热度', 'action-habit', S_ALL_STU, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], True),
]

print(f'前10类完成: {len(NEW_QUESTIONS)} 题')

# ===== work-career (24题) =====
NEW_QUESTIONS += [
    ('你对第一份工作的期望是', 'work-career', S_GRAD+S_CAREER, 'fc', 3,
     [('大厂高薪有面子', {'mbti.T':2,'enneagram.type3':2,'gallup.significance':1}),
      ('能学到东西有成长', {'mbti.N':2,'enneagram.type5':1,'gallup.learner':1}),
      ('稳定不加班就行', {'mbti.S':2,'enneagram.type6':1,'gallup.consistency':1}),
      ('做自己感兴趣的事', {'mbti.F':2,'enneagram.type4':1,'gallup.positivity':1})],
     ['significance','learner','consistency'], False),
    ('如果实习中领导让你打杂', 'work-career', S_UNDERGRAD+S_GRAD, 'fc', 3,
     [('认真做从小事学起', {'mbti.J':2,'enneagram.type1':1,'gallup.discipline':1}),
      ('跟领导说想做核心的', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('忍忍就过去了', {'mbti.P':1,'enneagram.type9':2,'gallup.adaptability':1}),
      ('考虑换个实习', {'mbti.P':2,'enneagram.type7':1,'gallup.activator':1})],
     ['discipline','command','adaptability'], False),
    ('你选择实习最看重', 'work-career', S_UNDERGRAD+S_GRAD, 'fc', 3,
     [('公司名气', {'mbti.T':2,'enneagram.type3':2,'gallup.significance':1}),
      ('能学到真本事', {'mbti.N':2,'enneagram.type5':1,'gallup.learner':1}),
      ('跟专业对口', {'mbti.S':1,'enneagram.type6':1,'gallup.consistency':1}),
      ('有转正机会', {'mbti.J':2,'enneagram.type1':1,'gallup.futuristic':1})],
     ['significance','learner','consistency'], False),
    ('你觉得理想的工作环境是', 'work-career', S_GRAD+S_CAREER, 'fc', 2,
     [('安静独立办公', {'mbti.I':2,'enneagram.type5':1,'gallup.focus':1}),
      ('开放式团队协作', {'mbti.E':2,'enneagram.type7':1,'gallup.communication':1}),
      ('灵活远程办公', {'mbti.P':2,'enneagram.type9':1,'gallup.adaptability':1}),
      ('户外或现场工作', {'holland.R':3,'mbti.S':1,'gallup.activator':1})],
     ['focus','communication','adaptability','activator'], False),
    ('毕业想去的城市', 'work-career', S_GRAD+S_CAREER, 'fc', 3,
     [('北上广深机会多', {'mbti.T':2,'enneagram.type3':1,'gallup.significance':1}),
      ('离家近方便照顾父母', {'mbti.F':2,'enneagram.type2':1,'gallup.connectedness':1}),
      ('新一线性价比高', {'mbti.N':2,'enneagram.type6':1,'gallup.strategic':1}),
      ('有山有水生活舒适', {'mbti.P':2,'enneagram.type9':1,'gallup.positivity':1})],
     ['significance','connectedness','strategic'], False),
    ('面试时被问到不会的问题', 'work-career', S_GRAD+S_CAREER, 'fc', 3,
     [('诚实说不知道', {'mbti.T':2,'enneagram.type1':1,'gallup.responsibility':1}),
      ('尝试从相关经验回答', {'mbti.N':2,'enneagram.type7':1,'gallup.strategic':1}),
      ('反问面试官更多细节', {'mbti.E':2,'enneagram.type3':1,'gallup.communication':1}),
      ('紧张说不出话', {'mbti.F':2,'enneagram.type6':1,'gallup.deliberative':1})],
     ['responsibility','strategic','communication'], False),
    ('如果工作和专业不对口', 'work-career', S_GRAD+S_CAREER, 'fc', 3,
     [('可以接受能力更重要', {'mbti.N':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('不能接受白学了', {'mbti.S':2,'enneagram.type1':1,'gallup.consistency':1}),
      ('看薪资和发展再定', {'mbti.T':2,'enneagram.type3':1,'gallup.maximizer':1}),
      ('有点担心但愿意试', {'mbti.F':1,'enneagram.type6':1,'gallup.deliberative':1})],
     ['adaptability','consistency','maximizer'], False),
    ('你更愿意做哪种工作', 'work-career', S_GRAD+S_CAREER, 'fc', 3,
     [('跟数据和分析打交道', {'holland.I':2,'mbti.T':2,'gallup.analytical':1}),
      ('跟人打交道', {'holland.S':2,'mbti.E':2,'gallup.communication':1}),
      ('跟技术和工具打交道', {'holland.R':3,'mbti.S':1,'gallup.activator':1}),
      ('跟创意和设计打交道', {'holland.A':2,'mbti.N':1,'gallup.ideation':1})],
     ['analytical','communication','activator','ideation'], False),
    # likert-4
    ('我觉得实习比上课更重要', 'work-career', S_UNDERGRAD+S_GRAD, 'lk', 3,
     {'holland.R':[0,1,2,3],'gallup.activator':[0,0,1,2],'mbti.S':[0,1,2,3]},
     ['activator','context'], False),
    ('我希望工作能帮助到别人', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.developer':[0,1,2,3]},
     ['developer','belief'], False),
    ('我能接受经常出差的工作', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.E':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','woo'], False),
    ('我希望工作有明确的晋升路径', 'work-career', S_GRAD+S_CAREER, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','achiever'], False),
    ('我觉得工作只是谋生手段', 'work-career', S_GRAD+S_CAREER, 'lk', 4,
     {'mbti.T':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], True),
    ('我愿意从基层岗位做起', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.discipline':[0,1,2,3]},
     ['discipline','context'], False),
    ('我觉得创业比打工更有前途', 'work-career', S_GRAD+S_CAREER, 'lk', 4,
     {'mbti.N':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.self_assurance':[0,1,2,3]},
     ['self_assurance','significance'], False),
    ('我希望工作和生活能平衡', 'work-career', S_GRAD+S_CAREER, 'lk', 2,
     {'mbti.P':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','adaptability'], False),
    ('我能接受加班但没有加班费', 'work-career', S_GRAD+S_CAREER, 'lk', 4,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.responsibility':[0,1,2,3]},
     ['responsibility','achiever'], True),
    ('我觉得技术类工作更有安全感', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'holland.R':[0,1,2,3],'mbti.T':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','analytical'], False),
    ('我希望工作中有自主决策权', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.N':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.command':[0,1,2,3]},
     ['command','self_assurance'], False),
    ('我觉得考公务员是好选择', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.consistency':[0,1,2,3]},
     ['consistency','deliberative'], False),
    ('我更喜欢项目制而不是固定工作', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','activator'], False),
    ('我觉得人脉比能力更重要', 'work-career', S_GRAD+S_CAREER, 'lk', 4,
     {'mbti.E':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.woo':[0,1,2,3]},
     ['woo','relator'], True),
    ('我愿意去偏远地区工作几年', 'work-career', S_GRAD+S_CAREER, 'lk', 4,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.belief':[0,1,2,3]},
     ['belief','developer'], False),
    ('我觉得第一份工作薪资最重要', 'work-career', S_GRAD+S_CAREER, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.achiever':[0,1,2,3]},
     ['achiever','significance'], True),
]

print(f'work-career 完成: {len(NEW_QUESTIONS)} 题')

# ===== decision-making (24题) =====
NEW_QUESTIONS += [
    ('填报志愿时你会', 'decision-making', S_SENIOR, 'fc', 4,
     [('自己做主', {'mbti.T':2,'enneagram.type8':1,'gallup.self_assurance':1}),
      ('主要听父母的', {'mbti.S':2,'enneagram.type6':1,'gallup.harmony':1}),
      ('综合大家意见', {'mbti.F':2,'enneagram.type9':1,'gallup.harmony':1}),
      ('咨询学长学姐', {'mbti.E':1,'enneagram.type6':1,'gallup.input':1})],
     ['self_assurance','harmony','input'], False),
    ('面对两个都喜欢的专业', 'decision-making', S_SENIOR+S_UNDERGRAD, 'fc', 4,
     [('选就业面更广的', {'mbti.T':2,'enneagram.type3':1,'gallup.futuristic':1}),
      ('选更感兴趣的', {'mbti.F':2,'enneagram.type4':1,'gallup.learner':1}),
      ('抛硬币听天由命', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1}),
      ('问很多人再做决定', {'mbti.E':2,'enneagram.type6':1,'gallup.input':1})],
     ['futuristic','learner','adaptability'], False),
    ('你在做重要决定前会', 'decision-making', S_ALL_STU, 'fc', 3,
     [('列出利弊清单', {'mbti.T':2,'enneagram.type1':1,'gallup.analytical':1}),
      ('跟着感觉走', {'mbti.F':2,'enneagram.type4':1,'gallup.self_assurance':1}),
      ('问身边信任的人', {'mbti.E':2,'enneagram.type2':1,'gallup.relator':1}),
      ('拖着到最后再说', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['analytical','self_assurance','relator'], False),
    ('考研还是直接工作你', 'decision-making', S_UNDERGRAD+S_GRAD, 'fc', 5,
     [('果断考研提升学历', {'mbti.J':2,'enneagram.type3':2,'gallup.achiever':1}),
      ('先工作积累经验', {'mbti.T':2,'enneagram.type8':1,'gallup.activator':1}),
      ('两手准备看情况', {'mbti.P':2,'enneagram.type6':1,'gallup.deliberative':1}),
      ('听家人建议', {'mbti.S':1,'enneagram.type6':1,'gallup.harmony':1})],
     ['achiever','activator','deliberative'], False),
    ('出国还是留在国内你', 'decision-making', S_UNDERGRAD+S_GRAD, 'fc', 5,
     [('出国开阔眼界', {'mbti.N':2,'enneagram.type7':1,'gallup.futuristic':1}),
      ('留在国内更安心', {'mbti.S':2,'enneagram.type6':1,'gallup.consistency':1}),
      ('看申请结果再定', {'mbti.P':2,'enneagram.type9':1,'gallup.adaptability':1}),
      ('看经济条件决定', {'mbti.T':2,'enneagram.type6':1,'gallup.deliberative':1})],
     ['futuristic','consistency','adaptability'], False),
    ('你在购物时会', 'decision-making', S_ALL_STU, 'fc', 1,
     [('货比三家再下单', {'mbti.T':2,'enneagram.type1':1,'gallup.analytical':1}),
      ('看上就买不纠结', {'mbti.P':2,'enneagram.type7':1,'gallup.activator':1}),
      ('先看评价再决定', {'mbti.S':1,'enneagram.type6':1,'gallup.input':1}),
      ('纠结很久最后不买', {'mbti.F':2,'enneagram.type6':1,'gallup.deliberative':1})],
     ['analytical','activator','input'], False),
    ('选课冲突时你会优先', 'decision-making', S_UNDERGRAD, 'fc', 2,
     [('必修课优先', {'mbti.J':2,'enneagram.type1':1,'gallup.responsibility':1}),
      ('感兴趣的课优先', {'mbti.F':2,'enneagram.type4':1,'gallup.learner':1}),
      ('给分高的课优先', {'mbti.T':1,'enneagram.type3':1,'gallup.maximizer':1}),
      ('时间合适的优先', {'mbti.S':1,'enneagram.type6':1,'gallup.adaptability':1})],
     ['responsibility','learner','maximizer'], False),
    ('面对多个社团邀请你会', 'decision-making', S_UNDERGRAD, 'fc', 2,
     [('选最有用的一个', {'mbti.T':2,'enneagram.type3':1,'gallup.maximizer':1}),
      ('选最感兴趣的', {'mbti.F':2,'enneagram.type7':1,'gallup.learner':1}),
      ('都试试再决定', {'mbti.P':1,'enneagram.type7':1,'gallup.adaptability':1}),
      ('都不参加', {'mbti.I':1,'enneagram.type5':1,'gallup.deliberative':1})],
     ['maximizer','learner','adaptability'], False),
    # likert-4
    ('我做决定前会收集大量信息', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'gallup.analytical':[0,1,2,3],'gallup.input':[0,0,1,2]},
     ['analytical','input'], False),
    ('我一旦做了决定就不后悔', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.self_assurance':[0,1,2,3]},
     ['self_assurance','command'], False),
    ('我经常改变已经做的决定', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], True),
    ('我觉得选择比努力更重要', 'decision-making', S_ALL_STU, 'lk', 4,
     {'mbti.N':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.strategic':[0,1,2,3]},
     ['strategic','futuristic'], False),
    ('我做决定很快不纠结', 'decision-making', S_ALL_STU, 'lk', 2,
     {'mbti.T':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.activator':[0,1,2,3]},
     ['activator','command'], False),
    ('我会因为怕后悔而不敢选择', 'decision-making', S_ALL_STU, 'lk', 3,
     {'enneagram.type6':[0,1,2,3],'gallup.deliberative':[0,1,2,3],'mbti.F':[0,0,1,2]},
     ['deliberative','analytical'], True),
    ('我觉得走弯路也是一种收获', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.positivity':[0,1,2,3]},
     ['positivity','context'], False),
    ('我会反复权衡后才做决定', 'decision-making', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','analytical'], False),
    ('我更相信数据而不是直觉', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.analytical':[0,1,2,3]},
     ['analytical','intellection'], False),
    ('我觉得别人的经验很有参考价值', 'decision-making', S_ALL_STU, 'lk', 2,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.input':[0,1,2,3]},
     ['input','context'], False),
    ('我习惯给每个选项打分再选', 'decision-making', S_ALL_STU, 'lk', 2,
     {'mbti.T':[0,1,2,3],'gallup.analytical':[0,1,2,3],'enneagram.type1':[0,0,1,2]},
     ['analytical','strategic'], False),
    ('我觉得计划赶不上变化', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], False),
    ('选专业时我优先考虑就业', 'decision-making', S_SENIOR+S_UNDERGRAD, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','maximizer'], False),
    ('我觉得留学能改变命运', 'decision-making', S_UNDERGRAD+S_GRAD, 'lk', 4,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','significance'], False),
    ('我更愿意走大多数人走过的路', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.consistency':[0,1,2,3]},
     ['consistency','context'], True),
    ('我觉得选择太多反而痛苦', 'decision-making', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.deliberative':[0,1,2,3]},
     ['deliberative','harmony'], False),
]

# ===== future-vision (24题) =====
NEW_QUESTIONS += [
    ('你想象中十年后的自己是', 'future-vision', S_ALL_STU, 'fc', 3,
     [('在某个领域有成就', {'mbti.N':2,'enneagram.type3':2,'gallup.significance':1}),
      ('家庭幸福安稳', {'mbti.F':2,'enneagram.type9':1,'gallup.connectedness':1}),
      ('环游世界自由自在', {'mbti.P':2,'enneagram.type7':2,'gallup.positivity':1}),
      ('还在探索中不确定', {'mbti.P':1,'enneagram.type5':1,'gallup.adaptability':1})],
     ['significance','connectedness','positivity'], False),
    ('如果可以实现一个愿望你选', 'future-vision', S_ALL_STU, 'fc', 3,
     [('考上理想学校', {'mbti.J':2,'enneagram.type3':1,'gallup.achiever':1}),
      ('家人健康平安', {'mbti.F':2,'enneagram.type2':1,'gallup.connectedness':1}),
      ('有花不完的钱', {'mbti.T':1,'enneagram.type8':1,'gallup.significance':1}),
      ('做自己喜欢的事', {'mbti.N':2,'enneagram.type4':1,'gallup.self_assurance':1})],
     ['achiever','connectedness','significance'], False),
    ('你对毕业后五年的规划是', 'future-vision', S_GRAD+S_CAREER, 'fc', 4,
     [('在大厂做到管理层', {'mbti.J':2,'enneagram.type3':2,'gallup.achiever':1}),
      ('创业做自己的项目', {'mbti.N':2,'enneagram.type8':2,'gallup.self_assurance':1}),
      ('考公务员求稳定', {'mbti.S':2,'enneagram.type6':1,'gallup.consistency':1}),
      ('还没想好走一步看一步', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['achiever','self_assurance','consistency'], False),
    ('你觉得自己适合在大城市还是小城', 'future-vision', S_ALL_STU, 'fc', 3,
     [('大城市机会多', {'mbti.E':2,'enneagram.type3':1,'gallup.significance':1}),
      ('小城市生活舒适', {'mbti.I':2,'enneagram.type9':1,'gallup.harmony':1}),
      ('都可以适应', {'mbti.P':2,'enneagram.type7':1,'gallup.adaptability':1}),
      ('没想好', {'mbti.F':1,'enneagram.type6':1,'gallup.deliberative':1})],
     ['significance','harmony','adaptability'], False),
    ('你最想过什么样的生活', 'future-vision', S_ALL_STU, 'fc', 3,
     [('充实有意义帮助他人', {'mbti.F':2,'enneagram.type2':2,'gallup.belief':1}),
      ('自由自在不被束缚', {'mbti.P':2,'enneagram.type7':1,'gallup.positivity':1}),
      ('功成名就受人尊敬', {'mbti.T':2,'enneagram.type3':2,'gallup.significance':1}),
      ('平静安稳无忧无虑', {'mbti.S':2,'enneagram.type9':1,'gallup.harmony':1})],
     ['belief','positivity','significance'], False),
    ('如果回到三年前你会', 'future-vision', S_ALL_STU, 'fc', 3,
     [('更努力学习', {'mbti.J':2,'enneagram.type1':1,'gallup.achiever':1}),
      ('多培养兴趣爱好', {'mbti.F':2,'enneagram.type4':1,'gallup.learner':1}),
      ('多交朋友', {'mbti.E':2,'enneagram.type7':1,'gallup.woo':1}),
      ('没什么想改变的', {'mbti.P':1,'enneagram.type9':1,'gallup.positivity':1})],
     ['achiever','learner','woo'], False),
    ('你对人工智能时代的看法', 'future-vision', S_ALL_STU, 'fc', 4,
     [('兴奋想参与其中', {'mbti.N':2,'enneagram.type7':1,'gallup.futuristic':1}),
      ('担心被取代', {'mbti.S':2,'enneagram.type6':1,'gallup.deliberative':1}),
      ('觉得是工具善加利用', {'mbti.T':2,'enneagram.type5':1,'gallup.strategic':1}),
      ('没太关注', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['futuristic','deliberative','strategic'], False),
    ('如果中了五百万你会', 'future-vision', S_ALL_STU, 'fc', 2,
     [('投资理财', {'mbti.T':2,'enneagram.type6':1,'gallup.deliberative':1}),
      ('环游世界', {'mbti.P':2,'enneagram.type7':2,'gallup.positivity':1}),
      ('创业做想做的事', {'mbti.N':2,'enneagram.type8':1,'gallup.self_assurance':1}),
      ('买房安定下来', {'mbti.S':2,'enneagram.type6':1,'gallup.consistency':1})],
     ['deliberative','positivity','self_assurance'], False),
    # likert-4
    ('我经常想象未来的生活', 'future-vision', S_ALL_STU, 'lk', 2,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','ideation'], False),
    ('我有清晰的人生目标', 'future-vision', S_ALL_STU, 'lk', 3,
     {'mbti.J':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.focus':[0,1,2,3]},
     ['focus','achiever'], False),
    ('我觉得青春就应该多尝试', 'future-vision', S_ALL_STU, 'lk', 2,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','positivity'], False),
    ('我担心以后找不到好工作', 'future-vision', S_ALL_STU, 'lk', 3,
     {'enneagram.type6':[0,1,2,3],'gallup.deliberative':[0,1,2,3],'mbti.S':[0,0,1,2]},
     ['deliberative','consistency'], True),
    ('我相信努力就会有回报', 'future-vision', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.achiever':[0,1,2,3]},
     ['achiever','belief'], False),
    ('我觉得命运掌握在自己手中', 'future-vision', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.self_assurance':[0,1,2,3]},
     ['self_assurance','command'], False),
    ('我想过出国留学的生活', 'future-vision', S_UNDERGRAD+S_GRAD, 'lk', 2,
     {'mbti.N':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.futuristic':[0,1,2,3]},
     ['futuristic','learner'], False),
    ('我觉得30岁前应该事业有成', 'future-vision', S_ALL_STU, 'lk', 4,
     {'mbti.J':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.achiever':[0,1,2,3]},
     ['achiever','significance'], True),
    ('我希望将来能财务自由', 'future-vision', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.significance':[0,1,2,3]},
     ['significance','achiever'], False),
    ('我觉得人生最重要的是开心', 'future-vision', S_ALL_STU, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.positivity':[0,1,2,3]},
     ['positivity','harmony'], False),
    ('我想过改变世界', 'future-vision', S_ALL_STU, 'lk', 4,
     {'mbti.N':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.significance':[0,1,2,3]},
     ['significance','futuristic'], False),
    ('我觉得平凡的生活也很好', 'future-vision', S_ALL_STU, 'lk', 3,
     {'mbti.S':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','positivity'], False),
    ('我有明确的时间规划', 'future-vision', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.discipline':[0,1,2,3]},
     ['discipline','focus'], False),
    ('我担心自己的选择是错的', 'future-vision', S_ALL_STU, 'lk', 3,
     {'enneagram.type6':[0,1,2,3],'gallup.deliberative':[0,1,2,3],'mbti.F':[0,0,1,2]},
     ['deliberative','analytical'], True),
    ('我觉得人生应该有一段gap year', 'future-vision', S_UNDERGRAD+S_GRAD, 'lk', 3,
     {'mbti.P':[0,1,2,3],'enneagram.type7':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','context'], False),
    ('我希望能成为某个领域的专家', 'future-vision', S_ALL_STU, 'lk', 3,
     {'mbti.N':[0,1,2,3],'enneagram.type5':[0,0,1,2],'gallup.learner':[0,1,2,3]},
     ['learner','significance'], False),
]

print(f'前16类完成: {len(NEW_QUESTIONS)} 题')

# ===== conflict-choice (21题) =====
NEW_QUESTIONS += [
    ('朋友让你帮忙作弊你会', 'conflict-choice', S_JUNIOR+S_SENIOR, 'fc', 4,
     [('坚决拒绝', {'mbti.T':2,'enneagram.type1':2,'gallup.consistency':1}),
      ('帮他这一次', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('假装没听见', {'mbti.P':1,'enneagram.type9':2,'gallup.harmony':1}),
      ('告诉他危害劝他放弃', {'mbti.F':1,'enneagram.type1':1,'gallup.developer':1})],
     ['consistency','empathy','harmony'], False),
    ('你觉得校规不合理的规定', 'conflict-choice', S_ALL_STU, 'fc', 3,
     [('遵守但可以建议改', {'mbti.J':2,'enneagram.type6':1,'gallup.responsibility':1}),
      ('直接违反不在乎', {'mbti.P':2,'enneagram.type8':1,'gallup.command':1}),
      ('表面遵守实际灵活', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1}),
      ('联合同学提出异议', {'mbti.E':2,'enneagram.type8':1,'gallup.command':1})],
     ['responsibility','command','adaptability'], False),
    ('班费使用有争议你会', 'conflict-choice', S_JUNIOR+S_SENIOR, 'fc', 3,
     [('提议投票表决', {'mbti.J':2,'enneagram.type6':1,'gallup.consistency':1}),
      ('听班长的', {'mbti.S':1,'enneagram.type6':1,'gallup.harmony':1}),
      ('坚持自己的观点', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('无所谓大家开心就好', {'mbti.F':2,'enneagram.type9':1,'gallup.harmony':1})],
     ['consistency','harmony','command'], False),
    ('和朋友同时喜欢上一个东西', 'conflict-choice', S_ALL_STU, 'fc', 3,
     [('让给朋友', {'mbti.F':2,'enneagram.type2':2,'gallup.empathy':1}),
      ('先到先得', {'mbti.T':2,'enneagram.type8':1,'gallup.competition':1}),
      ('商量轮流使用', {'mbti.J':2,'enneagram.type9':1,'gallup.harmony':1}),
      ('都不要了', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['empathy','competition','harmony'], False),
    ('家长逼你学不喜欢的特长', 'conflict-choice', S_JUNIOR+S_PARENT, 'fc', 3,
     [('坚持拒绝沟通', {'mbti.T':2,'enneagram.type8':1,'gallup.self_assurance':1}),
      ('先学着看看', {'mbti.P':2,'enneagram.type9':1,'gallup.adaptability':1}),
      ('表面学着实际放弃', {'mbti.P':1,'enneagram.type4':1,'gallup.adaptability':1}),
      ('找折中方案', {'mbti.F':2,'enneagram.type9':1,'gallup.harmony':1})],
     ['self_assurance','adaptability','harmony'], False),
    ('你觉得学习和谈恋爱', 'conflict-choice', S_SENIOR+S_UNDERGRAD, 'fc', 4,
     [('学习优先不能分心', {'mbti.J':2,'enneagram.type1':1,'gallup.focus':1}),
      ('可以兼顾', {'mbti.F':2,'enneagram.type7':1,'gallup.arranger':1}),
      ('看遇到什么人', {'mbti.P':1,'enneagram.type4':1,'gallup.adaptability':1}),
      ('谈恋爱也是学习', {'mbti.E':2,'enneagram.type2':1,'gallup.empathy':1})],
     ['focus','arranger','adaptability'], False),
    ('你觉得网络实名制', 'conflict-choice', S_ALL_STU, 'fc', 4,
     [('支持有利于环境', {'mbti.J':2,'enneagram.type1':1,'gallup.consistency':1}),
      ('反对侵犯隐私', {'mbti.N':2,'enneagram.type5':1,'gallup.deliberative':1}),
      ('有利有弊看情况', {'mbti.T':2,'enneagram.type6':1,'gallup.analytical':1}),
      ('没想法', {'mbti.P':1,'enneagram.type9':1,'gallup.adaptability':1})],
     ['consistency','deliberative','analytical'], False),
    ('同学借了你东西不还', 'conflict-choice', S_ALL_STU, 'fc', 2,
     [('直接要回来', {'mbti.T':2,'enneagram.type8':1,'gallup.command':1}),
      ('暗示提醒TA', {'mbti.F':2,'enneagram.type2':1,'gallup.empathy':1}),
      ('算了不值钱', {'mbti.P':1,'enneagram.type9':2,'gallup.adaptability':1}),
      ('下次不借了', {'mbti.J':1,'enneagram.type6':1,'gallup.deliberative':1})],
     ['command','empathy','adaptability'], False),
    # likert-4
    ('我觉得规则就是用来遵守的', 'conflict-choice', S_ALL_STU, 'lk', 2,
     {'mbti.J':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.consistency':[0,1,2,3]},
     ['consistency','discipline'], False),
    ('为了朋友我可以违反原则', 'conflict-choice', S_ALL_STU, 'lk', 4,
     {'mbti.F':[0,1,2,3],'enneagram.type2':[0,0,1,2],'gallup.empathy':[0,1,2,3]},
     ['empathy','relator'], True),
    ('我觉得大多数争议都有对错', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.analytical':[0,1,2,3]},
     ['analytical','consistency'], False),
    ('我能接受和自己观点不同的人', 'conflict-choice', S_ALL_STU, 'lk', 2,
     {'mbti.F':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','includer'], False),
    ('我觉得竞争是好事', 'conflict-choice', S_ALL_STU, 'lk', 2,
     {'mbti.T':[0,1,2,3],'enneagram.type3':[0,0,1,2],'gallup.competition':[0,1,2,3]},
     ['competition','achiever'], False),
    ('我宁可自己吃亏也不想伤和气', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','empathy'], False),
    ('我觉得有些事情没有对错', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.N':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','adaptability'], False),
    ('我敢在公开场合表达不同意见', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.E':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.command':[0,1,2,3]},
     ['command','self_assurance'], False),
    ('我觉得少数应该服从多数', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.J':[0,1,2,3],'enneagram.type6':[0,0,1,2],'gallup.consistency':[0,1,2,3]},
     ['consistency','harmony'], False),
    ('我会为了合群而改变自己', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.F':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.adaptability':[0,1,2,3]},
     ['adaptability','harmony'], True),
    ('我觉得吵架也是一种沟通', 'conflict-choice', S_ALL_STU, 'lk', 3,
     {'mbti.T':[0,1,2,3],'enneagram.type8':[0,0,1,2],'gallup.command':[0,1,2,3]},
     ['command','communication'], False),
    ('我宁愿沉默也不愿起冲突', 'conflict-choice', S_ALL_STU, 'lk', 2,
     {'mbti.I':[0,1,2,3],'enneagram.type9':[0,0,1,2],'gallup.harmony':[0,1,2,3]},
     ['harmony','deliberative'], False),
    ('我觉得公平比效率更重要', 'conflict-choice', S_ALL_STU, 'lk', 4,
     {'mbti.F':[0,1,2,3],'enneagram.type1':[0,0,1,2],'gallup.consistency':[0,1,2,3]},
     ['consistency','belief'], False),
]

# ===== 最终统计 =====
print(f'所有新题生成: {len(NEW_QUESTIONS)} 题')

# ========== 构建输出 ==========
output_items = []
qid = next_id
skipped = 0

for q_data in NEW_QUESTIONS:
    stem = q_data[0]
    cat = q_data[1]
    states = q_data[2]
    scale_type = q_data[3]
    diff = q_data[4]
    opts_or_map = q_data[5]
    themes = q_data[6]
    reverse = q_data[7] if len(q_data) > 7 else False

    # 检查重复
    ns = normalize(stem)
    if ns in existing_stems:
        skipped += 1
        continue

    # 构建 options
    if scale_type == 'fc':
        options = [{'text': t, 'score': s} for t, s in opts_or_map]
    else:  # likert-4
        sm = opts_or_map
        options = [
            {'text': '非常不符合', 'score': {k: v[0] for k, v in sm.items()}},
            {'text': '不太符合', 'score': {k: v[1] for k, v in sm.items()}},
            {'text': '比较符合', 'score': {k: v[2] for k, v in sm.items()}},
            {'text': '非常符合', 'score': {k: v[3] for k, v in sm.items()}},
        ]

    # 从score推导systems字段
    systems = set()
    for o in options:
        for k in o['score']:
            systems.add(k.split('.')[0])
    # gallup themes 存在则加上 gallup
    if themes:
        systems.add('gallup')

    item = {
        'id': f'Q{qid:04d}',
        'stem': stem,
        'category': cat,
        'scale': 'forced-choice' if scale_type == 'fc' else 'likert-4',
        'difficulty': diff,
        'reverse': reverse,
        'applicable_states': states,
        'systems': sorted(systems),
        'options': options,
        'gallup_themes': themes,
    }
    output_items.append(item)
    existing_stems.add(ns)
    qid += 1

print(f'有效新题: {len(output_items)} (跳过重复: {skipped})')

# 验证所有gallup_themes合法
invalid_themes = set()
for it in output_items:
    for t in it['gallup_themes']:
        if t not in VALID_THEMES:
            invalid_themes.add(t)
if invalid_themes:
    print(f'WARNING: 非法盖洛普主题: {invalid_themes}')

# 验证维度覆盖
en_covered = set(); mb_covered = set(); ho_covered = set(); ga_covered = set()
for it in output_items:
    for o in it['options']:
        for k in o['score']:
            p, s = k.split('.')
            if p == 'enneagram': en_covered.add(s)
            elif p == 'mbti': mb_covered.add(s)
            elif p == 'holland': ho_covered.add(s)
            elif p == 'gallup': ga_covered.add(s)

print(f'新题维度覆盖: en={len(en_covered)}, mb={len(mb_covered)}, ho={len(ho_covered)}, ga={len(ga_covered)}')
print(f'  Holland types: {sorted(ho_covered)}')

# 统计
cat_dist = Counter(it['category'] for it in output_items)
scale_dist = Counter(it['scale'] for it in output_items)
diff_dist = Counter(it['difficulty'] for it in output_items)
state_dist = Counter()
for it in output_items:
    for s in it['applicable_states']:
        state_dist[s] += 1

print(f'类别: {dict(sorted(cat_dist.items()))}')
print(f'量表: {dict(sorted(scale_dist.items()))}')
print(f'难度: {dict(sorted(diff_dist.items()))}')
print(f'状态: {dict(sorted(state_dist.items(), key=lambda x: -x[1]))}')

# ========== 追加到 items.jsonl ==========
with open(BANK_PATH, 'a', encoding='utf-8') as f:
    for it in output_items:
        f.write(json.dumps(it, ensure_ascii=False) + '\n')

print(f'\n已追加到 {BANK_PATH}')
print(f'题库总量: {len(existing) + len(output_items)}')
